### ISSUE TITLE
Support to ILI9342C ?

### ISSUE THREAD

**Issue by clasik** [gaboze-express/Odroid-GO-ILI9342#1]
Will you do support Driver ILI9342**C**, also?
[Like RetroESP32 2.7](https://github.com/retro-esp32/RetroESP32/commit/a40e0553935e9ee49dda1d3d7b4e61d9d10ffeb3):
https://github.com/retro-esp32/RetroESP32/commit/a40e0553935e9ee49dda1d3d7b4e61d9d10ffeb3

I would like compile the original Ordoid-Go Firmware with ILI9342**C** Driver.

Datasheet: https://cdn.datasheetspdf.com/pdf-down/I/L/I/ILI9342C-ILITEK.pdf

**Comment by 32teeth** [comment]
Yeah, this is something we can do.

Don't forget about the [Sponsor](https://github.com/sponsors/retro-esp32) link
Every cup of coffee helps

**Comment by clasik** [comment]
@32teeth, I have analized your commit in the RetroESP32 repository:  #https://github.com/retro-esp32/RetroESP32/commit/d9d20162ade68638e18a8c4e60b1839ed8466e53#diff-9ce89dfc356f6cebbccd157f5d93dac0380e75efaf5f5d67a283a542dbf12833 and it seen as only need this 2 lines for adapt the ILI9342C driver, is it correct?
However, I tried this change in Odroid-Go-Firmware original, and it does not work :(
